pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: fivem-dev

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    from: fivem-dev
    repo: spritsail/fivem
    tags:
      - 'latest'
      - '%label org.label-schema.version'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure] }
    secrets: [ webhook_url, notify_token ]
