#!/bin/sh

if [ -n "$DEBUG" ]; then
    set -x
fi

if [ -z "${NO_DEFAULT_CONFIG}" ]; then
    while : ; do
        [[ -f "${SUBDIR}/server.cfg" ]] && break
        echo "Waiting for repo to sync."
        sleep 30
    done
fi

if [ -n "$SUBDIR" ]; then
    cd $SUBDIR
fi

CONFIG_ARGS=$CONFIG_ARGS
if [ -z "${NO_DEFAULT_CONFIG}" ]; then
  CONFIG_ARGS="$CONFIG_ARGS +exec ${SUBDIR}/server.cfg"
fi

if [ -z "${NO_LICENSE_KEY}" ]; then
  if [ -z "${LICENCE_KEY}" ]; then
    echo "Licence key not found in environment, please create one at https://keymaster.fivem.net!"
    exit 1
  fi
  CONFIG_ARGS="$CONFIG_ARGS +set sv_licenseKey ${LICENCE_KEY}"
fi

exec /opt/cfx-server/FXServer \
       +set citizen_dir /opt/cfx-server/citizen/ \
       $CONFIG_ARGS \
       $@
